name: commit

on:
  push:
    branches:
      - "*"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

#    - name: Setup and start ssh-agent
#      uses: webfactory/ssh-agent@v0.5.3
#      with:
#        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerRegistry
      uses: docker/login-action@v1
      with:
        registry: registry.devcodemylife.tech
        username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
        password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      run: |
        make
      with:
        push: true
        context: .
        tags: registry.devcodemylife.tech/devcodemylife/backend_frontend:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
